#!/bin/bash
#SBATCH --mail-user=jjk451@mail.harvard.edu
#SBATCH -n 10
#SBATCH -J shortbred_AllMG
#SBATCH -o shortbred_AllMG_out.txt
#SBATCH -e shortbred_AllMG_err.txt
#SBATCH --mail-type=BEGIN



module load hpc/python-2.7.1_full_stack
module load bio/ncbi-blast-2.2.27+
module load hpc/scons-2.1.0_python-2.7.1
module load hpc/EMBOSS-6.4.0
module load bio/cd-hit-v4.6-2012-04-25
module load bio/muscle-3.8.31
module load bio/ncbi-blast-2.2.28+
module load math/R-3.0.1
module list

#mkdir /n/regal/huttenhower_lab/jkaminski/YAT
#mkdir /n/regal/HMP
#mkdir /n/regal/T2D
#mkdir /n/regal/T2D

python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20716.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20716 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20716RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20717.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20717 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20717RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20718.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20718 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20718RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20719.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20719 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20719RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20720.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20720 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20720RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20721.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20721 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20721RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20722.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20722 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20722RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20723.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20723 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20723RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20724.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20724 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20724RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20725.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20725 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20725RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20726.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20726 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20726RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20727.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20727 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20727RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20728.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20728 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20728RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20729.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20729 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20729RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20730.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20730 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20730RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20731.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20731 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20731RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20732.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20732 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20732RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20733.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20733 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20733RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20734.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20734 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20734RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20735.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20735 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20735RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20736.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20736 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20736RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20737.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20737 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20737RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20738.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20738 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20738RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20739.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20739 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20739RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20740.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20740 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20740RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20741.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20741 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20741RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20742.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20742 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20742RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20743.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20743 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20743RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20744.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20744 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20744RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20745.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20745 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20745RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20746.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20746 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20746RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20747.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20747 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20747RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20748.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20748 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20748RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20749.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20749 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20749RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20750.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20750 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20750RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20751.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20751 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20751RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20752.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20752 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20752RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20753.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20753 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20753RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20755.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20755 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20755RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20756.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20756 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20756RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20757.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20757 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20757RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20758.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20758 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20758RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20759.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20759 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20759RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20760.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20760 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20760RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20761.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20761 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20761RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20762.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20762 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20762RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20763.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20763 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20763RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20764.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20764 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20764RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20765.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20765 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20765RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20766.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20766 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20766RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20767.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20767 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20767RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20768.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20768 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20768RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20769.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20769 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20769RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20770.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20770 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20770RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20771.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20771 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20771RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20772.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20772 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20772RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20773.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20773 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20773RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20774.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20774 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20774RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20775.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20775 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20775RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20776.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20776 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20776RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20777.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20777 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20777RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20779.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20779 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20779RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20780.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20780 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20780RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20781.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20781 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20781RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20782.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20782 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20782RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20783.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20783 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20783RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20784.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20784 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20784RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20785.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20785 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20785RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20786.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20786 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20786RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20787.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20787 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20787RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20788.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20788 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20788RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20789.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20789 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20789RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20790.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20790 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20790RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20791.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20791 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20791RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20792.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20792 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20792RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20793.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20793 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20793RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20794.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20794 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20794RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20795.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20795 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20795RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20796.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20796 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20796RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20797.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20797 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20797RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20798.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20798 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20798RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20799.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20799 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20799RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20800.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20800 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20800RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20801.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20801 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20801RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20802.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20802 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20802RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20803.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20803 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20803RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20804.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20804 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20804RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20805.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20805 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20805RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20806.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20806 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20806RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20807.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20807 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20807RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20808.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20808 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20808RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20809.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20809 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20809RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20810.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20810 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20810RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20811.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20811 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20811RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20812.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20812 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20812RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20813.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20813 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20813RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20814.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20814 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20814RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20815.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20815 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20815RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20816.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20816 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20816RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20817.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20817 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20817RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20818.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20818 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20818RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20821.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20821 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20821RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20822.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20822 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20822RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20823.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20823 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20823RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20824.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20824 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20824RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20825.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20825 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20825RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
python /n/huttenhower_lab/data/shortbred/shortbred_doit/src/shortbred/shortbred_quantify.py --markers /n/huttenhower_lab/data/shortbred/shortbred_doit/out/init_markers/ARDBfilter_WashU/85/clust/clust.faa --threads 2 --wgs /n/huttenhower_lab_nobackup/downloads/Yatsunenko/wgs/20826.fna --tmp /n/regal/huttenhower_lab/jkaminski/YAT/20826 --id 0.95 --results /n/huttenhower_lab/data/shortbred/shortbred_doit/out/human_mg_results/YAT/20826RPKM.out --minreadBP 200 --avgreadBP 450 --usearch /n/home11/jkaminski/usearch/usearch --notmarkers Y
